version: 2.1
orbs:
  node: circleci/node@1.1.6
  cypress: cypress-io/cypress@1.23.0
jobs:
  build-and-test:
    executor:
      name: node/default
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: yarn install
            - run: sed -i '/process.env.CI/,+7 d' node_modules/react-scripts/scripts/start.js
            - run: yarn ci
workflows:
  build-and-test:
    jobs:
      - build-and-test
