version: 2.1
orbs:
  cypress: cypress-io/cypress@1.29.0
jobs:
  build:
    docker:
      - image: cimg/node:16.7.0-browsers
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          name: Restore Yarn Package Cache
          keys:
            - yarn-packages-{{ checksum "yarn.lock" }}
      - run:
          name: Install Dependencies
          command: yarn install --immutable
      - save_cache:
          name: Save Yarn Package Cache
          key: yarn-packages-{{ checksum "yarn.lock" }}
          paths:
            - .yarn/cache
            - .yarn/unplugged
      # https://github.com/facebook/create-react-app/issues/8688#issuecomment-620607944
      - run: sed -i '/process.env.CI/,+7 d' node_modules/react-scripts/scripts/start.js
      - run: yarn lint
      - run: yarn ci
