version: 2.1
orbs:
  node: circleci/node@1.1.6
  browser-tools: circleci/browser-tools@1.0.1
  cypress: cypress-io/cypress@1.23.0
jobs:
  build-and-test:
    executor:
      name: node/default
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: yarn install
            - run: yarn ci
workflows:
  build-and-test:
    jobs:
      - build-and-test
